; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
 
#define MyAppName "Sundial"
;#define MyAppVersion "0.2.11"
#define MyAppVersion GetEnv('SD_VERSION')
#define MyAppPublisher "Ralvie AI Inc,"
;#define MyAppURL "https://Sundial.net/"
#define MyAppExeName "sd-main.exe"
#define RootDir "..\.."
#define DistDir "..\..\dist"

#pragma verboselevel 9
 
[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
; TODO: Should probably remove the extra leading {, but don't want to risk changing the AppId...
AppId={{F226B8F4-3244-46E6-901D-0CE8035423E4}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
;AppPublisherURL={#MyAppURL}
;AppSupportURL="https://github.com/Sundial/Sundial/issues"
;AppUpdatesURL="https://github.com/Sundial/Sundial/releases"
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
PrivilegesRequired=lowest
;PrivilegesRequiredOverridesAllowed=dialog
OutputDir={#DistDir}
OutputBaseFilename=Sundial-setup
SetupIconFile="{#RootDir}\sd-qt\media\logo\logo.ico"
UninstallDisplayName={#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
Compression=lzma
SolidCompression=yes
WizardStyle=modern

; can be removed the following
;Compression Parameters
;Please note while Compression=lzma/ultra and InternalCompressLevel=Ultra are better than max
;they also require 320 MB of memory for compression. If you're system has at least 256MB RAM then by all
;means set it to ultra before compilation
;;Compression=lzma/ultra
;;InternalCompressLevel=ultra
;;SolidCompression=true
 
[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"


[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
 
[Files]
Source: "{#DistDir}\Sundial\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DistDir}\Sundial\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
 
[UninstallDelete]
Type: filesandordirs; Name: "{app}\*"
Type: filesandordirs; Name: "{userstartup}\{#MyAppName}.lnk"
Type: dirifempty; Name: "{autopf}\{#MyAppName}"
;Type: dirifempty; Name: "{userappdata}\{#MyAppName}"
; Add any additional uninstallation cleanup steps here, such as removing registry entries
 
[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Comment: "Sundial";
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; Comment: "Sundial";
 
[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
 
; Removes the previously installed version before installing the new one
; NOTE: Doesn't work? And also discouraged by the docs
 
[InstallDelete]
Type: filesandordirs; Name: "{app}\"
 
[Code]
var
  InstalledPathArray: array of String;
  
/////////////////////////////////////////////////////////////////////
// The following uninstall code was found at:
// https://stackoverflow.com/questions/2000296/innosetup-how-to-automatically-uninstall-previous-installed-version
// and than modified to work in a 32/64 bit environment
/////////////////////////////////////////////////////////////////////
function GetUninstallStrings(): array of String;
var
	sUnInstPath: String;
	sUnInstallString: String;
	asUninstallStrings : array of String;
	index : Integer;
begin
	sUnInstPath := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\{#emit SetupSetting("AppId")}_is1');
	sUnInstallString := '';
	index := 0;

	// Retrieve uninstall string from HKLM32 or HKCU32
	if RegQueryStringValue(HKLM32, sUnInstPath, 'UninstallString', sUnInstallString) then
	begin
		SetArrayLength(asUninstallStrings, index + 1);
		asUninstallStrings[index] := sUnInstallString;
		index := index +1;
	end;

	if RegQueryStringValue(HKCU32, sUnInstPath, 'UninstallString', sUnInstallString) then
	begin
		SetArrayLength(asUninstallStrings, index + 1);
		asUninstallStrings[index] := sUnInstallString;
		index := index +1;
	end;

	// Only for Windows with 64 bit support: Retrieve uninstall string from HKLM64 or HKCU64
	if IsWin64 then
	begin
		if RegQueryStringValue(HKLM64, sUnInstPath, 'UninstallString', sUnInstallString) then
		begin
			SetArrayLength(asUninstallStrings, index + 1);
			asUninstallStrings[index] := sUnInstallString;
			index := index +1;
		end;

		if RegQueryStringValue(HKCU64, sUnInstPath, 'UninstallString', sUnInstallString) then
		begin
			SetArrayLength(asUninstallStrings, index + 1);
			asUninstallStrings[index] := sUnInstallString;
			index := index +1;
		end;
	end;
	Result := asUninstallStrings;
end;

/////////////////////////////////////////////////////////////////////
procedure UnInstallOldVersions();
var
	sUnInstallString: String;
	index: Integer;
	isUninstallMade: Boolean;
	iResultCode : Integer;
	asUninstallStrings : array of String;
begin
	isUninstallMade := false;
	asUninstallStrings := GetUninstallStrings();
	for index := 0 to (GetArrayLength(asUninstallStrings) -1) do
	begin
		sUnInstallString := RemoveQuotes(asUninstallStrings[index]);
		if Exec(sUnInstallString, '/SILENT /NORESTART /SUPPRESSMSGBOXES','', SW_HIDE, ewWaitUntilTerminated, iResultCode) then
			isUninstallMade := true;
	end;

	// Wait a few seconds to prevent installation issues, otherwise files are removed in one process while the other tries to link to them
	if (isUninstallMade) then
		Sleep(2000);
end;

/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// End of unstall code
/////////////////////////////////////////////////////////////////////

function IsProcessRunning(const AProcessName: string): Boolean;
var
  ResultCode: Integer;
begin
  // Use the tasklist command to check if the process is running
  Exec('cmd.exe', '/C tasklist /FI "IMAGENAME eq ' + AProcessName + '" | find /I "' + AProcessName + '"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  // If find returns 0, the process is running
  Result := (ResultCode = 0);
end;
 
procedure StopApplication();
var
  ResultCode: Integer;
  ProcessesStopped: Boolean;
  MsgResult: Integer;
begin
  // Initialize the flag to track if any process was stopped
  ProcessesStopped := False;
 
  // Check and stop each process
  if IsProcessRunning('{#MyAppExeName}') then
  begin
    Exec('taskkill', '/F /IM {#MyAppExeName}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    ProcessesStopped := True;
  end;
 
  if IsProcessRunning('sd-watcher-window.exe') then
  begin
    Exec('taskkill', '/F /IM sd-watcher-window.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    ProcessesStopped := True;
  end;
 
  if IsProcessRunning('sd-watcher-afk.exe') then
  begin
    Exec('taskkill', '/F /IM sd-watcher-afk.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    ProcessesStopped := True;
  end;
 
  if IsProcessRunning('sd-server.exe') then
  begin
    Exec('taskkill', '/F /IM sd-server.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    ProcessesStopped := True;
  end;
 
  // Show message only if processes were stopped
  if ProcessesStopped then
  begin
    MsgResult := MsgBox('The application has been stopped successfully. Uninstallation will continue.', mbInformation, MB_OKCancel);
    if MsgResult <> IDOK then
    begin
      Abort;  // Abort the uninstallation process
    end;
  end;
end;


procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  MsgResult: Integer;
begin
  if CurUninstallStep = usUninstall then
  begin
    MsgResult := MsgBox('Warning: This action will completely remove the application and its files.', mbInformation, MB_OK);
    if MsgResult <> IDOK then
    begin
      Abort;  // Abort if the user cancels or closes the dialog
    end;
 
    StopApplication();

  end;
end;

function InitializeSetup(): Boolean;	
var
  MsgResult: Integer;
begin
  InstalledPathArray := GetUninstallStrings();
  if Length(InstalledPathArray) > 0  then
	begin
		MsgResult := MsgBox('An older version of Sundial  has been installed. It will be uninstalled before proceeding.', mbInformation, MB_OKCancel);
		if MsgResult <> IDOK then
		begin
			Abort;  // Abort if the user cancels or closes the dialog
			Result := False;
		end;
	
		StopApplication();
		UnInstallOldVersions();
		Result := True;		
	end
  else
	begin 
	 Result := True;
	end;
end;
